import type { Metadata } from "next";
import { exo2 } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "Slug Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo2.className} flex h-screen items-center antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
